* TODO self.assertSomething skapar inte exceptions
- Python unittest loggar p책 n책got s채tt om ett assertSomehting har uppfyllts eller inte.
- N채r en assertX inte har uppfyllts, har testet misslyckats, vilket loggas.
- 
